server:
  port: 8012
  sessionTimeout: 15
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8

spring:
  application:
    name: eurekaserverprovider

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://root:melo@localhost:8001/eureka/

db:
  product:
    url: jdbc:postgresql://localhost:5432/zhaopin_db?prepareThreshold=0
    username: postgres
    password: 123456