server:
  port: 8007
spring:
  cloud:
    config:
      profile: dev
      label: master
      uri: http://localhost:8888/
      discovery:
        enabled: true
  application:
    name: configclient

management:
  security:
    enabled: false
