server:
  port: 8180
  sessionTimeout: 15
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8

spring:
  application:
    name: serviceRibbonHystrix

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:melo@localhost:8001/eureka/

EUREKASERVERPROVIDER:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#访问地址：http://localhost:8180/hystrix，输入http://localhost:8180/hystrix.stream,点击monitor Stream进入监控页面
