server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/DoitwellAnd/config.git
          search-paths: config
management:
  security:
    enabled: false
