server:
  port: 8181
  sessionTimeout: 15
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8

spring:
  application:
    name: serviceFeign

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:melo@localhost:8001/eureka/