server:
  port: 9090
  sessionTimeout: 15
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8

spring:
  application:
    name: serviceHystrix

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:angus@localhost:8001/eureka/

EUREKASERVERPROVIDER:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
